language: node_js
node_js:
  - '8.0.0'
services:
  - mongodb
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
sudo: required
before_script: npm i -g eslint mocha
# ::::::::: added this block for travis || also chrome-headless-launcher
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run test
